chi_square test, to check the association in between two categorical variables

In [1]:
import pandas as pd
import numpy as np
from scipy import stats as stat
from scipy.stats import chi2_contingency,chi2
import seaborn as sns


In [2]:
tip = sns.load_dataset('tips')
tip.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
dataset = pd.crosstab(tip['sex'],tip['smoker'])
dataset 
## transformed both categorical variables

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [4]:
observed_values = dataset.values
observed_values

array([[60, 97],
       [33, 54]], dtype=int64)

In [6]:
alpha = 0.05
## set the alpha "level of signinficance"

In [5]:
chi2_contingency(observed_values)

(0.0,
 1.0,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [6]:
expected_values = chi2_contingency(observed_values)[3]
expected_values,observed_values

## and now you can see check there is very minued difference in between 
## observed values and expected value.
## and chi_square test calculates the difference between observed and expected value
## and based on the differnce we can make our decissions.


(array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]),
 array([[60, 97],
        [33, 54]], dtype=int64))

In [7]:
### calculate the degree of freedom
## degree of freedom = no_of_categories - 1
no_of_rows = len(dataset.iloc[0:2,0])
no_of_columns = len(dataset.iloc[0,0:2])
DOF = (no_of_rows-1)*(no_of_columns-1)
alphaa = 0.5
print(f"degree of freedom :- {DOF} AND alphaa :- {alphaa}")

degree of freedom :- 1 AND alphaa :- 0.5


In [12]:
[(o-e)**2./e for o,e in zip(observed_values,expected_values)]

[array([0.00042693, 0.00026294]), array([0.00077044, 0.00047451])]

In [14]:
chi2_square_stats = sum([(o-e)**2./e for o,e in zip(observed_values,expected_values)])
chi2_square_stats
## i am adding both result as by formula


array([0.00119737, 0.00073745])

In [15]:
statistic = chi2_square_stats[0]+chi2_square_stats[1]
statistic

## now we have statistics value and then we will
## compare with this value by critical value

0.001934818536627623

In [18]:
### finding critical value
## Q  ==> CONFIDENT INTERVAL 1 - ALPHA
## DF ==> DEGREE OF FREEDOM
CRITICAL_VALUE = chi2.ppf(q = 1-alphaa,df=DOF)
CRITICAL_VALUE

0.454936423119572

In [19]:
## check the condition for null hypothesis
## Ho   ==> THERE IS NO ASSOCIATION
## H1   ==> THERE IS ASSOCIATION

if CRITICAL_VALUE>=statistic:
    print("accept null hypothesis , there is no association in between 2 categorical value")
else:
    print("reject null hypothesis, there is association in between two cat variables")

accept null hypothesis , there is no association in between 2 categorical value


In [22]:
### You can also check condition by using P_value
### now i am checking condition of association using P_value

p_value = 1-chi2.cdf(x=statistic,df=DOF)
p_value

0.964915107315732

In [24]:
### Now check the condition of Hypothesis using P_value
if p_value >=alphaa:
    print("accept Null Hypothesis, there is no relation" )
else:
    print("reject Null Hypothesis , there is relation in between variables")

accept Null Hypothesis, there is no relation


### HOME WORK FOR PRECTISE
## Write a complete function to find out the association in between more than 2 
## variables using critical value. and function should  be able to return, all those
## variables name as a list, which are having association  in between variables
## then you can easily, drop out all those variables for training.